# Generated by Django 3.1.7 on 2021-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('unique_squirrel_id', models.CharField(max_length=200, unique=True)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=15)),
                ('Date', models.DateField(help_text='date when the squirre is found')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='the age of the squirrel', max_length=15)),
                ('Primary_Fur_Color', models.CharField(max_length=200)),
                ('Location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Gound Plane', 'Ground Plane')], help_text='the Location of the squirrel', max_length=15)),
                ('Specific_Location', models.TextField(blank=True)),
                ('running', models.BooleanField(blank=True, null=True)),
                ('chasing', models.BooleanField(blank=True, null=True)),
                ('climbing', models.BooleanField(blank=True, null=True)),
                ('eating', models.BooleanField(blank=True, null=True)),
                ('foraging', models.BooleanField(blank=True, null=True)),
                ('other_activities', models.CharField(blank=True, max_length=200, null=True)),
                ('kuks', models.BooleanField(blank=True, null=True)),
                ('quaas', models.BooleanField(blank=True, null=True)),
                ('moans', models.BooleanField(blank=True, null=True)),
                ('tail_flags', models.BooleanField(blank=True, null=True)),
                ('tail_twitches', models.BooleanField(blank=True, null=True)),
                ('approaches', models.BooleanField(blank=True, null=True)),
                ('indifferent', models.BooleanField(blank=True, null=True)),
                ('runs_from', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
