# Generated by Django 3.1.7 on 2021-04-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='unique_squirrel_id',
            new_name='Unique_Squirrel_ID',
        ),
    ]
